version: '3'

services:
  db:
    image: mysql
    container_name: my_database
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - my_infra_network

networks:
  my_infra_network:
    name: my_infra_network