version: '3'

services:
  db:
    image: postgres
    container_name: my_database
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432
    networks:
      - my_infra_network

networks:
  my_infra_network:
    name: my_infra_network